### ISSUE TITLE
Watch out guys, this is 99.9% fake

### ISSUE THREAD

**Issue by buran-energia** [MinerProxy/WiseNoDevFee#4]
The source code doesn't contain most of the advertised features, rather just has some old hack for an old miner version for Eth that definitely isn't working on the likes of TRex. I couldn't also find source code for "DevModule.dll".

In other words, if you will run the binaries, it will probably steal hashes from you at best and the attacker will gain full control over computer at worst.

**Comment by cyjyyd** [comment]
Calm down,if it cotains all the features in the source code,how long do you think it will last on github?

If you are sure it is 99.9% fake,talk is cheap,show me the proof.

**Comment by wisebuilder** [comment]
I am very sorry that starting from the official version of 1.0.12, there are too many mining core secrets. If all the source code is released, this software will not survive for 3 days. More than one guy wanted to buy the source code from me, but I refused. I think this brother is also one of them. In the qq group and private me, they tried to try to get the source code from me. I am very sorry, in order to make this software is a bit longer, and I won’t give you the latest core source code whatever you say.This is also to protect the interests of me and my group friends
